refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)} [{l}] - {m}{n})}"
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "[{d}] - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
loggers:
  app::backend::db:
    level: error
  app::requests:
    level: error
    appenders:
      - requests
    additive: false