name: "build"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: copy config
      env: 
        WHO_TO_TRUST: ${{ secrets.REACT }}
      run: echo "$WHO_TO_TRUST" > src/Config.ts
    - name: install dependencies (ubuntu only)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang libdbus-1-dev libgtk-3-dev libnotify-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib curl gperf bison python3-dbusmock openjdk-8-jre
    - name: install dependencies
      run: npm install
    - name: copy config.ts
      run: cp electron/config.ts.template electron/config.ts
    - name: build application
      run: npm run electron:build
