name: Create Release
on:
  push:
    branches:
      - main
jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      LATEST_TAG_NAME: ""
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get latest tag name
      run: echo "LATEST_TAG_NAME=$(git tag | sort -V | tail -1)" >> $GITHUB_ENV
    - name: Debug latest tag name
      run: echo "Latest tag name:${{ env.LATEST_TAG_NAME }}"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.LATEST_TAG_NAME }}
        release_name: Release ${{ env.LATEST_TAG_NAME }}
        body: Automated release created by GitHub Actions.
        draft: false
        prerelease: false
    - name: Debug create release output
      run: echo "${{ steps.create_release.outputs }}"

