name: "test-on-pr"
on: [push]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo dpkg --add-architecture arm64
        sudo apt-get update -y
        sudo apt install -y --no-install-recommends g++-aarch64-linux-gnu libc6-dev-arm64-cross libssl-dev:arm64 libwebkit2gtk-4.0-dev:arm64 build-essential curl:arm64 wget:arm64 libgtk-3-dev:arm64 patchelf:arm64 librsvg2-dev:arm64 pkg-config
        rustup target add aarch64-unknown-linux-gnu
        rustup toolchain install stable-aarch64-unknown-linux-gnu
        cargo install tauri-cli --git https://github.com/tauri-apps/tauri
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc CC_aarch64-unknown-linux-gnu=aarch64-linux-gnu-gcc CXX_aarch64-unknown-linux-gnu=aarch64-linux-gnu-g++ PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig PKG_CONFIG_ALLOW_CROSS=1
    - name: update cargo
      run: cargo update
      working-directory: ./workee/src-tauri
    - name: install app dependencies and build it
      run: yarn && yarn build
      working-directory: ./workee

    
    - name: build workee (ubuntu only)
      if: matrix.platform == 'debian-latest'
      run: |
        cargo tauri build --target aarch64-unknown-linux-gnu
    