name: Versionning
on:
  push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Get current branch name
      id: get_branch
      shell: bash
      run: | 
        echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV    
    - name: Extract semantic version from branch name
      id: extract_version
      run: |
        echo ${{ env.BRANCH_NAME }}
        version=$(echo "${{env.BRANCH_NAME}}" | grep -oP "\d+\.\d+\.\d+") >> $GITHUB_ENV
        echo ${{env.version}}
    - name: Create tag
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      run: |
        #!/bin/bash
        git tag $version
        git tag -l
        GITHUB_TOKEN=$GITHUB_TOKEN hub release $version 
    - name: Push tags
      run: git push -u origin --tags

