name: Versionning
on:
  push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Get current branch name
      id: get_branch
      run: | 
        echo ::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})
    - name: Extract semantic version from branch name
      id: extract_version
      run: |
        version=$(echo "${{steps.get_branch.outputs.branch_name}}" | grep -oP "(\d+\.\d+\.\d+)")
        echo ::set-output name=version::$version
    - name: Check if branch name matches version
      if: ! $version
      run: echo "Branch name does not match version format."
        exit 1
    - name: Create tag
      uses: actions/create-release@v1
      with:
        tag_name: "${{steps.extract_version.outputs.version}}"
    - name: Push tags
      run: git push -u origin "${{steps.extract_version.outputs.version}}"
