name: Versionning
on:
  push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Get current branch name
      id: get_branch
      run: | 
        echo ::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})
    - name: Extract semantic version from branch name
      id: extract_version
      run: |
        version=$(echo "${{steps.get_branch.outputs.branch_name}}" | grep -oP "(\d+\.\d+\.\d+)")
        echo ::set-output name=version::$version
    - name: Create tag
      run: |
        echo "${version}"
        git tag ${version}
        git tag
        
    - name: Push tags
      run: git push -u origin --tags

