name: Versionning
on:
  push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Get current branch name
      id: get_branch
      run: | 
        echo ::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})
    - name: Extract semantic version from branch name
      run: |
        "${{ steps.get_branch.outputs.branch_name }} | grep -oP version-(\d+\.\d+\.\d+" >> SEMANTIC_VERSION
        if [[ ! ${SEMANTIC_VERSION} ]]; then
          echo "Branch name does not match version format, please use the format version: X.Y.Z"
          exit 1
    - name: Create tag
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.get_branch.outputs.semantic_version }}
    - name: Push tags
      run: git push origin ${{ steps.get_branch.outputs.semantic_version }}
    - name: Success message
      if: success()
      run: echo "Successfully created new tag version ${SEMANTIC_VERSION}"
